### ISSUE TITLE
Problem with foreign key and restrict-get_field 

### ISSUE THREAD

**Issue by smorillon** [robocc/ros2-django#1]
Branch : restrict-get_field 

We have an object xxx which has several objects yyy across a one to many relationship

When the `GetYyy` service is created, the following constant is generated at the service level:
`string FIELD_ID_XXX=id_xxx`

If we call the `GetYyy` service with the fields containing `FIELD_ID_XXX` the following error is generated:

`Got exception yyy has no field name 'id_xxx' `

**Comment by xouillet** [comment]
Fixed in `[eaf67cb](https://github.com/robocc/ros2-django/commit/eaf67cb05b0f288b75a529231e49c47c47d74c51)`.

Thanks for reporting, have a wonderful day
